// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dtuagfxysqmdprriyxzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dWFnZnh5c3FtZHBycml5eHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MjgyMTYsImV4cCI6MjA4NjAwNDIxNn0.Yirc2BZVPSZesMtssLvWr4my0K5cXgjp5A_c-4yK-Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);